export const data = {
    languages: [
      "Amharic",
      "Bambara",
      "Chichewa",
      "Ewe",
      "Hausa",
      "Igbo",
      "Kinyarwanda",
      "Lingala",
      "Luganda",
      "Malagasy",
      "Oromo",
      "Sepedi",
      "Sesotho",
      "Shona",
      "Somali",
      "Swahili",
      "Tigrinya",
      "Tsonga",
      "Twi",
      "Xhosa",
      "Yoruba",
      "Zulu",
      // Namibian languages
      "Nama",
      "Oshiwambo",
      "Herero",
      "Rukwangali",
      "Kavango",
      "Damara",
      "Silozi"
    ],
  };